### ISSUE TITLE
strips disconnect everyday

### ISSUE THREAD

**Issue by Adaaks** [wez/govee-lan-hass#25] opened 2023-05-27 19:35 UTC
strips disconnect everyday, have to restart home assistant to get it fixed temp, please try to get it fixed, scrolling down the community forum people are having the same issue! https://community.home-assistant.io/t/govee-integration/228516

debug code

2023-05-08 22:32:09.578 DEBUG (MainThread) [custom_components.govee_lan.light] timeout while querying device state for E4:26:D4:AD:FC:49:F8:68 light.strips
Traceback (most recent call last):
File "/usr/local/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/config/custom_components/govee_lan/light.py", line 420, in async_update
await self._govee_controller.update_device_state(self._govee_device)
File "/usr/local/lib/python3.10/site-packages/govee_led_wez/govee.py", line 287, in update_device_state
await asyncio.wait_for(future, timeout=self.device_control_timeout)
File "/usr/local/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

**Comment by wez** [comment] 2023-05-27 20:34
Duplicate of your own existing issue https://github.com/wez/govee-lan-hass/issues/19

**Closed by wez** 2023-05-27 20:34 UTC
